### ISSUE TITLE
Calculation of error bars in https://github.com/NMRLipids/MATCH/blob/master/scripts/calcOrderParameters.py

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/MATCH#39]
The error is now calculated as
    def get_avg_std_stem_OP(self):
        """
        Provides average, stddev and standard error of mean for all OPs in self.traj
        """
        self.means = np.mean(self.traj, axis=0)
        return ( np.mean(self.traj), 
                 np.std(self.traj), 
                 np.std(self.means) )  
between lines https://github.com/NMRLipids/MATCH/blob/baedee851e3e0a1e1c970068ce433bcd7b99450c/scripts/calcOrderParameters.py#L163 and  https://github.com/NMRLipids/MATCH/blob/baedee851e3e0a1e1c970068ce433bcd7b99450c/scripts/calcOrderParameters.py#L166

I have little bit hard time to read the code, but it looks to me that the last term may not be the standard error of the mean over different lipids. 

This part is introduced in this commit: https://github.com/NMRLipids/MATCH/commit/8cdf112658753a036bdb932f1a35645eb2f38c87#diff-9059634b554f11adeebe965a046f656b

After a quick look, the version before this commit seems to calculate the standard error of the mean. Also, the error bars calculated after the commit seems to be larger than with the version before (after a quick tests).

**Comment by jmelcr** [comment]
It will be much clearer after knowing, how the trajectory is "constructed".
Each order parameter has a separate object (here referenced as self), which contains its trajectory.
Each such a trajectory has a simple hierarchy (can be understood as indices in a large 2D array):
1. each residue of interest (as many as there are in the topology)
2. instantaneous value of the order parameter = frame for each time step  (as many as frames in the trajectory)

The line
` self.means = np.mean(self.traj, axis=0) `
calculates "meanS" -- the mean value separately for each residue (due to the axis=0 option).
Hence, self.means contains a list of order parameters per each residue.
Having that, calculating the standard error of the mean is simple:
`np.std(self.means)`
this line calculates the standard deviation of the means, which is exactly what we want. 

Note that the used notation assumes that all trajectories for each residue are of the same length, which is, however, valid for all applications using the code. 

The method get_avg_std_stem_OP returns: 
`return ( np.mean(self.traj), 
              np.std(self.traj), 
              np.std(self.means) ) `
which gives in order:
- the order parameter from all residues and frames (i.e. the average value of all instantaneous parameters)
- its standard deviation
- and the standard error of the mean.

**Comment by ohsOllila** [comment]
Thanks, this is clear. However, we want to have the standard error of the mean over different lipids, not the standard deviation. Therefore, we should divide the np.std(self.means) with the square root of number of the lipids in the line:
return ( np.mean(self.traj), np.std(self.traj), np.std(self.means) )
How can we read the number of lipids from the self.traj?

**Comment by ohsOllila** [comment]
I figured it out myself and corrected in the commit: https://github.com/NMRLipids/MATCH/commit/62b9086894fd73d5d6a5d2e28ee8d7ce9d975771

**Comment by jmelcr** [comment]
I see -- I saw it from a different point when I was writing the code. 
If the standard error, not deviation or variance of individual means, is desired, the correction seems correct!
